Feat/student demo
rojikaru/python-oop pull request #1
Opened 2024-09-25 08:09 UTC by rojikaru

2024-09-26 19:29 UTC, dmytro-maherovskyi-lpnu requested changes
Good job, but requires minor corrections

2024-09-26 19:29 UTC, dmytro-maherovskyi-lpnu commented on Lab2/main.py
> +    print(f'{student.name}\'s grant:', student.grant_size())
This print is used several times, can be extracted as a method

2024-09-26 19:29 UTC, dmytro-maherovskyi-lpnu commented on Lab2/main.py
> +    print(f'{fp_student.name}\'s balance:', fp_student.get_balance())
Same here

2024-09-26 19:29 UTC, dmytro-maherovskyi-lpnu commented on Lab2/models/student.py
> +        if 1 <= score <= 5:
Magic numbers should be set as enums or constants

2024-09-26 19:29 UTC, dmytro-maherovskyi-lpnu commented on Lab2/models/student.py
> +                return 1000
Magic numbers here as well

2024-09-27 10:32 UTC, rojikaru commented on Lab2/main.py
> +    print(f'{student.name}\'s grant:', student.grant_size())
Done

2024-09-27 10:33 UTC, rojikaru commented on Lab2/main.py
> +    print(f'{fp_student.name}\'s balance:', fp_student.get_balance())
Done

2024-09-27 10:33 UTC, rojikaru commented on Lab2/models/student.py
> +        if 1 <= score <= 5:
Done

2024-09-27 10:33 UTC, rojikaru commented on Lab2/models/student.py
> +                return 1000
Fixed

2024-09-30 19:35 UTC, dmytro-maherovskyi-lpnu approved these changes

2024-10-01 05:22 UTC, merged